name: Update Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '4 * 1,2 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Update
      run: node --no-warnings --experimental-specifier-resolution=node update/stats.mjs
    - name: Test
      run: npm run test
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Stats ($(date --date="$(date +%Y-%m-1) -1 month" "+%Y-%m"))" || exit 0
        git push
